### ISSUE TITLE
Validierung: "The document contains capital letter I within Fraktur text" sollte nicht innerhalb von <note type="editorial"> gelten

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#10]
Beispiel: Mein Frakturtext enthält nur `J`, keine `I`.
Aber in einer editorischen Anmerkung möchte ich einige *I*nformationen ergänzen und schreibe dabei 'normal' mit I/J-Unterscheidung. Das gibt dann eine (orange) Fehlermeldung, ist aber irritierend.
Daher: `<note type="editorial">Verwendung von "I"</note>` sollte keine Fehlermeldung erzeugen.

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
