### ISSUE TITLE
DTABf und somit auch Vorlagedatei ist nicht (mehr) TEI_all-valide

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#100]
Vgl. https://www.deutschestextarchiv.de/files/vorlage_basisformat.xml mit RNG-Schema https://tei-c.org/Vault/P5/1.7.0/xml/tei/custom/schema/relaxng/tei_all.rng:

![image](https://user-images.githubusercontent.com/13750091/119791778-6bc02c80-bed5-11eb-88f7-e80c5d12d335.png)

= DTABf ist nicht (mehr) TEI_all-valide!

**Comment by susannehaaf** [comment]
Das hier verlinkte Schema repräsentiert die TEI P5-Guidelines der Version 1.7.0. Diese ist sehr alt. Die TEI-Guidelines sind bei Version [4.4.0](https://tei-c.org/Vault/P5/4.4.0/xml/tei/custom/schema/relaxng/tei_all.rng). Die Validierung gegen diese Version bzw. gegen [das aktuelle Schema](http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng) klappt. Ich schließe das Ticket somit.
