### ISSUE TITLE
Doku Listen: Implizites Leerzeichen bei <hi> oder Tippfehler?

### ISSUE THREAD

**Issue by teoric** [deutschestextarchiv/dtabf#101]
Beim folgendem Beispiel von <https://www.deutschestextarchiv.de/doku/basisformat/liAllg.html>
```xml
<list>
   <item>[...]</item>
   <item>
     <hi rendition="#aq">s)</hi>Der erſte Stein <hi rendition="#aq">a</hi>,
       auf dem Gewölbefuß liegend, heißt: <hi rendition="#g">An-<lb/>
     fänger</hi>- oder <hi rendition="#g">Kämpferſtein</hi>.
   </item><lb/>
```
sieht es so aus, als würde `<hi>` so interpretiert, als ob ein implizites ein Leerzeichen stünde. Das verwundert, denn dann verschwömmen die Wortgrenzen und man könnte 
```xml
Kaffee<hi>kanne</hi> nicht Kaffee<hi>tasse</hi>
```
nicht von
```xml
Kaffee <hi>kanne</hi> , nicht Kaffee <hi>tasse</hi>
```
unterscheiden.  Ist das tatsächlich so intendiert?

@cthomasdta hat dankenswerterweise eine Formatierung des Textes mit explizitem Leerzeichen herausgesucht:  <https://www.deutschestextarchiv.de/book/download_xml/wanderley_bauconstructionslehre02_1878>.
```xml
<p><hi rendition="#aq">s)</hi> Der er&#x017F;te Stein
```
(Das klärt allerdings nicht, ob es auch implizite gibt bzw. das Leerzeichen vor `Der` redundant ist.)

**Comment by cthomasdta** [comment]
> (Das klärt allerdings nicht, ob es auch implizite gibt bzw. das Leerzeichen vor `Der` redundant ist.)

Ich meinte das so, dass da m.E. die Doku falsch ist: Das Leerzeichen vor `Der` ist *nicht* redundant, sondern notwendig und sollte im Beispiel in der Doku ergänzt werden.

**Comment by tboenig** [comment]
Meiner Meinung: **ein Tippfehler.** 
Danke @teoric.

In diesem Zusammenhang überprüfen:  https://www.deutschestextarchiv.de/doku/basisformat/typogrAllg.html 
ist zu präzisieren: Wie korrekt Leerzeichen transkribiert werden sollten.

**Comment by susannehaaf** [comment]
Vielen Dank für den Hinweis. Ich habe das Beispiel korrigiert und [in der Doku](https://www.deutschestextarchiv.de/doku/basisformat/trGrundsaetze) explizite Infos zu Leerzeichen ergänzt. Beim nächsten Doku-Update (in Kürze) sind die Änderungen sichtbar.
