### ISSUE TITLE
Darstellungsfehler: geschwungene Klammer wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#107]
Vgl. das hier https://deutschestextarchiv.de/doku/basisformat/klTabelle verlinkte Beispiel
https://www.deutschestextarchiv.de/schleicher_indogermanische02_1862/399 

Die mit `#leftBraced` kodierten geschwungenen Klammern (in Tabellenzellen[*]) werden nicht mehr angezeigt. Ich erinnere mich sicher, dass das mal der Fall war. @haoess hast du an den Stylesheets was geändert, kannst du bitte schauen?

[*] Kodierung ebd. z.B.:
```XML
          <row>
            <cell>Nomin.</cell>
            <cell> <hi rendition="#i">dobryj</hi> </cell>
            <cell>für <hi rendition="#i">dobr&#x016D;-&#x012D;</hi></cell>
            <cell>grdf.d.endg.</cell>
            <cell> <hi rendition="#i">-as-ja-s</hi> </cell>
            <cell rendition="#leftBraced" rows="2">ntr. <hi rendition="#i">dobroje,</hi><lb/>
grdf. d. endg.<lb/><hi rendition="#i">-am-jat</hi> oder<lb/>
vill. <hi rendition="#i">-at-jat</hi></cell>
          </row>

**Comment by cthomasdta** [comment]
Hier in der Berner Edition https://humboldt.unibe.ch/text/1798-Observations_faites_a-1 funktioniert es noch, vgl. die zweite Tabelle:
![image](https://user-images.githubusercontent.com/13750091/138078577-6720152b-fb3a-4fc1-8646-056918611ad7.png)


= gleichartig kodiert, z.B.:
```XML
<row>
                        <cell rows="2" rendition="#rightBraced">30 me&#x017F;&#x017F;idor (18<lb break="yes"/>juillet), à midi.</cell>
                        <cell>22. 10.</cell>
                        <cell>22. 12.</cell>
                        <cell/>
                        <cell/>
                    </row>

**Comment by cthomasdta** [comment]
> Vgl. das hier https://deutschestextarchiv.de/doku/basisformat/klTabelle verlinkte Beispiel https://www.deutschestextarchiv.de/schleicher_indogermanische02_1862/399
> 
> Die mit `#leftBraced` kodierten geschwungenen Klammern (in Tabellenzellen[*]) werden nicht mehr angezeigt. 

P.S. Hier https://www.deutschestextarchiv.de/gotter_erbschleicher_1789/8 dagegen, in einer Liste, ist die Darstellung der geschwungenen Klammer noch da:

![image](https://user-images.githubusercontent.com/13750091/138097177-ff01b6b4-8547-41dc-a52b-b617b4f36a04.png)

**Comment by haoess** [comment]
Danke, ist behoben.
