### ISSUE TITLE
Doku: Beispiel "(Sinntragender) Abstand zwischen Absätzen" fehlerhaft

### ISSUE THREAD

**Issue by StefanDumont** [deutschestextarchiv/dtabf#13]
Wenn mich nicht alles täuscht, fehlt in dem Beispiel "(Sinntragender) Abstand zwischen Absätzen" im [Abschnitt "Absätze"](http://deutschestextarchiv.de/doku/basisformat/absatz.html) das in Rede stehende Element `<space dim="vertical" />`. Außerdem wäre vielleicht ein Link zum [Abschnitt "Leerraum"](http://deutschestextarchiv.de/doku/basisformat/leerraum.html) an der Stelle auch ganz praktischt.

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
