### ISSUE TITLE
Schema(tron): Regel: <subst> muss <del> UND <add> enthalten

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#14]
Bisher ist auch valide:
`<subst><add place="across">kälteſten</add></subst>`
oder 
`<subst><del rendition="#ow">kälteſten</add></subst>`
aber `<subst>` anzuwenden ist nur sinnvoll, wenn es eine Streichung `<del>` gibt, die durch eine Hinzufügung `<add>` ersetzt wird.

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
