### ISSUE TITLE
Schema und Doku: gebrochene Tabellen

### ISSUE THREAD

**Issue by funkyfuture** [deutschestextarchiv/dtabf#25]
das schema erlaubt ggw. keine `<cb>` oder `<pb>`-elemente innerhalb von `<table>`-elementen.

- [TEI reference](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-table.html)

**Comment by susannehaaf** [comment]
Doch, beide Elemente sind im DTABf-Schema im `<table>`-Element erlaubt. Am Verhältnis der Elemente zueinander ändert sich im DTABf-RNG gegenüber dem TEI-Tagset grundsätzlich nichts. Es kann lediglich sein, dass die Schematron-Validierung (basisformat.sch) hier zusätzliche Constraints einführt. Dies ist aber für das genannte Szenario nicht der Fall.

**Comment by funkyfuture** [comment]
stimmt, mein fehler war, startendes und beendendes `<cb>`-element vor bzw. nach dem `<table>`-element zu setzen. insofern könnte solch ein szenario der doku zu tabellen hinzugefügt werden.
