### ISSUE TITLE
Doku: Fehler(chen)

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#30]
Siehe z.B. hier http://www.deutschestextarchiv.de/doku/basisformat/geProsa

Das obere Beispiel sollte m.E. auch <lb/> am Zeilenende enthalten:

```
<lg type="poem">
  <head>[Titel]</head> <!-- sofern vorhanden -->
  <lg n="[Strophennummer]"> <!-- sofern kein einstrophiges Gedicht -->
    <l>[Vers]</l>**<lb/>**
    <l>[Vers]</l>**<lb/>**
  </lg>
</lg>
```

Das ist aber bei vielen anderen Einträgen scheinbar ebenso, siehe z.B. http://www.deutschestextarchiv.de/doku/basisformat/brAllg.html . Auch hier keine <lb/> am Anfang, dann in den DTA-Beispielen natürlich schon. Fehler oder Absicht?

**Comment by susannehaaf** [comment]
Das Beispiel in geProsa.html habe ich korrigiert. Im allg. Teil von brAllg.html ist es Absicht, dass keine Zeilenumbrüche drin sind: diese Kodierung basiert auf keiner Quelle, insofern kann es, muss aber nicht sein, dass im konkreten Fall dann jeweils `<lb/>s` stehen.
