### ISSUE TITLE
Doku: "Signatur des Empfängers" = "Signatur des *Absenders*"

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#31]
Siehe http://www.deutschestextarchiv.de/doku/basisformat/brAllg.html?hl=empf%C3%A4nger, 

"Die Signatur des **Empfängers** unter einem Brief steht im <closer> im Element <signed>."

> "Signatur des Empfängers"
= "Signatur des Absenders"

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
