### ISSUE TITLE
fehlerhafte Darstellung von <note type="editorial"> innerhalb von <closer> und <salute>

### ISSUE THREAD

**Issue by sgoettel** [deutschestextarchiv/dtabf#35]
Die note wird im closer (und salute?) nicht korrekt dargestellt, siehe folgendes Bsp. der editorial note nach "Sprachlehre" unter
(http://www.deutschestextarchiv.de/dtaq/book/view/sanders_volger_1876?p=3&view=)

**Comment by haoess** [comment]
Darstellungsfehler, hat nix mit dem Schema zu tun. Ist schon gefixt.
