### ISSUE TITLE
Benutzung von ref mit target-Attribut spezifizieren

### ISSUE THREAD

**Issue by rettinghaus** [deutschestextarchiv/dtabf#36]
Beispiel: http://www.deutschestextarchiv.de/book/show/fischer_collegienhefte_1826
Hier sind im Inhaltsverzeichnis die ref-Elemente mit target-Attributen versehen, um auf die entsprechenden Seiten (Faksimiles) zu verweisen. Diese Möglichkeit wird in der Doku aber nicht genannt. 
Bei der Übersicht der Elemente wird lapidar angemerkt, dass `@target` eine "Referenz auf eine externe Ressource" darstelle, was der Verwendungsart im angegebenen Beispiel widerspräche.

**Comment by susannehaaf** [comment]
Stimmt, danke für den Hinweis!

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
