### ISSUE TITLE
Doku: Umbrüche bei Absätzen

### ISSUE THREAD

**Issue by rettinghaus** [deutschestextarchiv/dtabf#38]
In der Doku steht
> Allein die Elemente `<pb>`, `<cb>`, und `<space>` stehen ohne folgendes <lb>-Element. 

Die Beispiel-Absätze zeigen aber ein `<lb/>`
http://www.deutschestextarchiv.de/doku/basisformat/absatz.html

vgl. auch #33

**Comment by susannehaaf** [comment]
Ja, auf <p> folgt <lb/>. Nur bei Seiten- und Spaltenumbrüchen (<pb>, <cb>) und beim Leerraum (<space>) steht kein folgendes <lb>.
