### ISSUE TITLE
<bibl> sollte auch innerhalb von <note type="editorial"> zulässig sein.

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#40]
Vgl. z.B. 
`                        <cit><quote>
                            <lg type="poem">
                                <head rendition="#c">Jahrestag.</head><lb/>
                                
                                <l>Mit einer Fichte
<choice><sic>auf</sic><corr>in</corr></choice><note type="editorial">Zur
Korrektur des Druckfehlers vgl. die entsprechende Zeile in <bibl><ref
target="http://resolver.staatsbibliothek-berlin.de/SBB0001A3C500030019">George,
Stefan: Die Bücher der Hirten- und Preisgedichte · der Sagen und Sänge und
der hängenden Gärten / [Zeichnung von Jan Toorop]. In: Ders.: Gesamt-Ausgabe
der Werke, Bd. 3. Berlin, 1930, S. [11]</ref></bibl>: „Mit einer fichte in
den wiesen stehn“.</note> den Wiesen stehn,</l><lb/>
                                
                            </lg>
                        </quote></cit>`

Fehlermeldung
> [E0003] Element "bibl" not allowed within element "quote".

Das gemeinte `<bibl>` steht innerhalb meiner `<note type="editorial">`; dort sollte es erlaubt sein.

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
