### ISSUE TITLE
"capital letter I" sollte in Frakturtexten innerhalb von <note type="editorial"> keine Warnung auslösen.

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#41]
Vgl. z.B.
<cit><quote> <lg type="poem"> <head rendition="#c">Jahrestag.</head><lb/>  <l>Mit einer Fichte <choice><sic>auf</sic><corr>in</corr></choice><note type="editorial">Zur Korrektur des Druckfehlers vgl. die entsprechende Zeile in <bibl><ref target="http://resolver.staatsbibliothek-berlin.de/SBB0001A3C500030019">George, Stefan: Die Bücher der Hirten- und Preisgedichte · der Sagen und Sänge und der hängenden Gärten / [Zeichnung von Jan Toorop]. In: Ders.: Gesamt-Ausgabe der Werke, Bd. 3. Berlin, 1930, S. [11]</ref></bibl>: „Mit einer fichte in den wiesen stehn“.</note> den Wiesen stehn,</l><lb/>  </lg> </quote></cit>

Fehlermeldung

> [W0004] The document contains capital letter I within Fraktur text. […]

Das gemeinte "capital letter I" steht innerhalb meiner <note type="editorial">; dort sollte es erlaubt sein.

**Comment by xlhrld** [comment]
Müsste nicht strenggenommen der Schriftschnitt für editorische Ergänzungen explizit auf »Antiqua«  gesetzt werden? Sonst wären die wohl formal alle auch in Fraktur zu setzen. Das würde vermutlich auch die Warnung verschwinden lassen. Klingt für mich nicht nach Infrastruktur-Bug sondern nach einer Unschärfe in der Basisformat-Doku.

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)

**Comment by susannehaaf** [comment]
@xlhrld : `@rendition`-Angaben sind eigentlich primär für die Kodierung der Gegebenheiten der Textvorlage gedacht. Dass sie auch rendering-Angaben für die digitale Textausgabe werden, ist ein erwünschter Nebeneffekt. Metainformationen zum Text sollten nicht mit entsprechenden rendering-Informationen ausgezeichnet werden müssen. Der hier beschriebene Fall kann außerdem leicht in Schematron abgefangen werden 

Das Ticket gab es doppelt (s. #10 ). Problem ist gelöst.
