### ISSUE TITLE
dtabf/documentation/introduction_en.dita enthält kaputte URL

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#47]
das hier verlinkte Dokument
http://www.deutschestextarchiv.de/doku/basisformat/vorlage_basisformat.xml ist woanders: 
> Not Found
> The requested URL /doku/basisformat/vorlage_basisformat.xml was not found on this server.
> Apache/2.2.22 (Debian) Server at www.deutschestextarchiv.de Port 80

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
