### ISSUE TITLE
Adopt a versioning scheme

### ISSUE THREAD

**Issue by xlhrld** [deutschestextarchiv/dtabf#56]
When disseminating new iterations of the DTABf guidelines it will be necessary to adopt a versioning scheme. There exists a formal description of the three-number-scheme (a.k.a. semantic versioning) at https://semver.org/spec/v2.0.0.html which I think could be used as is. As the DTABf is already used in production, I think it would be reasonable to eventually release it as `1.0.0` at some point (in the not so far future) and from then on follow the semantic versioning scheme.

(This issue serves as a reminder to a steering group discussion.)

**Comment by funkyfuture** [comment]
i doubt that there will be different maintained branches of the schema and the accompanying documentation that would require the semantics of semantic versioning. using these semantics should even raise expectations of bugfix-only releases for former major and minor versions. hence using [CalVer](https://calver.org/) could be a viable, simple alternative.

**Comment by susannehaaf** [comment]
Since v1.0.0 we are using a versioning scheme for DTABf.
