### ISSUE TITLE
No fixed value for publisher/@xml:id

### ISSUE THREAD

**Issue by xlhrld** [deutschestextarchiv/dtabf#59]
The value of `publicationStmt/@xml:id` is currently fixed to `DTACorpusPublisher`. I assume that's for some internal reasons concerning the publication pipeline. However, for people outside the project this exact value makes little sense and it should probably be relaxed to any URI.

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0): `"DTACorpusPublisher"` is now optional; other values are possible.
