### ISSUE TITLE
Zitierempfehlung für DTABf geben

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#64]
Wie z.B. ist diese Seite zu zitieren, http://www.deutschestextarchiv.de/doku/basisformat/trNasalstrich.html, wie das DTABf insgesamt?

**Comment by cthomasdta** [comment]
(noch) nicht seitengenau, aber inzwischen vorhanden im Footer:
> Zitierempfehlung: "DTABf. Deutsches Textarchiv – Basisformat (2011–2020), hrsg. v. d. Berlin-Brandenburgischen Akademie der Wissenschaften.
> <http://deutschestextarchiv.de/doku/basisformat>." Bitte beachten Sie auch die Publikationen zum DTABf.

Was meint ihr alle, genügt das so?

**Comment by susannehaaf** [comment]
Ich finde schon. Habe jetzt allerdings mal das Datum aktualisiert. ;-) (Sichtbar in Kürze...) Kann das Ticket dann zu, @cthomasdta ?

**Comment by cthomasdta** [comment]
> Ich finde schon. Habe jetzt allerdings mal das Datum aktualisiert. ;-) (Sichtbar in Kürze...) Kann das Ticket dann zu, @cthomasdta ?

sehr schön, danke dir! Ich schließe das Issue.
