### ISSUE TITLE
add @facs in DTABf-Doku at /doku/basisformat/abbKennzeichnung.html

### ISSUE THREAD

**Issue by mhug** [deutschestextarchiv/dtabf#65]
Bei der Dokumentation der "Grundstruktur der Kodierung von Abbildungen" fehlt der Link zur Abbildung, siehe: http://www.deutschestextarchiv.de/doku/basisformat/abbKennzeichnung.html

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
