### ISSUE TITLE
Doku: idno

### ISSUE THREAD

**Issue by susannehaaf** [deutschestextarchiv/dtabf#68]
@susannehaaf: at http://deutschestextarchiv.de/doku/basisformat/mdSdMsDesc.html of all the possible values for `idno/@type` only four are actually specified (`shelfmark`, `URLCatalogue`, `URLImages`, `PPN`). The other values (such as `URLTCF`) should also be documented.

_Originally posted by @xlhrld in https://github.com/deutschestextarchiv/dtabf/issues/43#issuecomment-457087238_

**Comment by cthomasdta** [comment]
`PPN` seems not to be working yet.

+ it would be useful to add `idno/type="VD"` to document zu VD16-, VD17-, VD18-number

**Comment by susannehaaf** [comment]
documentation updated and @type="VD" inserted with v1.1.0
