### ISSUE TITLE
Vorschlag: hi-Wert für Großbuchstaben einführen

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#77]
Analog zu Kapitälchen `<hi rendition="#k">` sollten auch GROSSBUCHSTABEN nicht zwingend als solche getippt werden müssen. Ich hätte gern die Option, `<hi rendition="#caps">` dazu sagen. 

Hintergrund: Mehr durch Zufall fiel mir auf, dass einige Analysewerkzeuge (und sicher auch Website-Indexer) sonst Probleme mit der Interpretation haben. So interpretiert CAB z.B. `<hi rendition="#caps">Hum-<lb/>boldt</hi>` anders als `HUM-<lb/>BOLDT`, was nicht korrekt analysiert wird.

**Comment by wrznr** [comment]
Das halte ich für grundfalsch. Großbuchstaben sind keine Frage der Darstellung sondern andere Zeichen. Auch Kapitälchen müssen m.E. als `H<hi rendition="#k">UMBOLDT</hi>` umgesetzt werden, um klar zu machen, dass es sich um eine Darstellungsvarianz der umschlossenen Buchstaben handelt (ähnlich Fett- und Kursivdruck).

**Comment by StefanDumont** [comment]
Naja, bin skeptisch, dass wir das brauchen. Der Analysefall von CAB ist ja schon sehr speziell. Fragt sich wie oft so eine Konstallation vorkommt. Die gängigen Indexer (wie z.B. der Lucene Index; aber natürlich auch die Suchmaschinen) gehen über Groß- und Kleinschreibung i.d.R. erstmal hinweg, wenn nicht speziell anders konfiguriert. 

@wrznr Großbuchstaben sind andere Zeichen, Kapitälchen auch, das stimmt. Wenn man Kapitälchen tatsächlich also solche setzen würde, müsste man es aber nicht mehr eigens taggen. Dem gegenüber sind Fett- und Kursivdruck aber keine eigenen Zeichen, sondern hängen an der verwendeten Schriftart.

**Comment by cthomasdta** [comment]
Ok, ich ziehe aufgrund der Einwände den Vorschlag zurück. Ich schließe das issue.

**Comment by wrznr** [comment]
@StefanDumont Nur zur Sicherstellung: Großbuchstaben und Kapitälchen sind die **gleichen** Zeichen! M.E. verhält sich ein *a* zu einem **a** wie ein A zu einem `A`. I.e. ich tippe immer das gleiche, um das Zeichen zu realisieren.

**Comment by StefanDumont** [comment]
Jein, in Unicode gibt es eigene Areas für Kapitälchen und verwendet ein Font diese auch korrekterweise (ansonsten gibt es die "falschen Kapitälchen", die sich in Strichstärke von den normalen Großbuchstaben unterscheiden). Tatsächlich kann man das in den meisten Programmen aber korrekt aus Klein- und Großbuchstaben erzeugen, das stimmt. Ich kenne aber keine Regel, nach der das so oder so erfolgen muss. Rein tyopraphisch und vom Druckprozess her gesehen schreibt man es normalerweise "normal" und markiert es dann als Kapitälchen.

**Comment by nolda** [comment]
Als Maintainer eines OpenType-Fonts mit Kapitälchen (Lingua Franca) kann ich vielleicht etwas zur Klarstellung beitragen.
OpenType-Fonts kodieren Kapitälchen (wie andere typographische Varianten) i. d. R. als Zeichen in der Private Use Area und beziehen diese mittels des OpenType-Features `smcp` auf die entsprechende Gemeine (Minuskel), die im Font am normalen Unicode-Codepunkt kodiert ist. Manche Fonts wie Lingua Franca haben darüber hinaus das OpenType-Feature `c2sc`, mit dem Kapitälchen auf die entsprechende Versalie (Majuskel) an dem entsprechenden Unicode-Codepunkt bezogen werden.
Die Unicode-Codepunkte für Kapitälchen sind nicht für 'normale' typographische Kapitälchen gedacht, sondern für phonetische Zeichen.
OpenType-Fonts behandeln Kapitälchen also normalerweise als typographische Varianten von Minuskeln, deren Unicode-Kodierung idiosynkratisch (PUA) ist.

**Comment by textloop** [comment]
@nolda, kleine Nachfrage dazu: 
Und wie wäre das dann bei `small caps`? 
Wenn man 
![image](https://user-images.githubusercontent.com/7046115/72346192-b886d700-36d5-11ea-8325-32665e5096ab.png)

als `<hi rendition="#smcaps">Small Caps</hi>` transkribiert und auszeichnet. Und damit `<valItem ident="#smcap"><desc>font-variant: small-caps</desc></valItem>` meint. 
Ist das dann korrekt?

**Comment by nolda** [comment]
Ja, richtig. In CSS bewirkt `font-variant: small-caps` wie das OpenType-Feature `smcp`, dass Minuskeln durch Kapitälchen ersetzt werden, während Majuskeln unverändert bleiben.

**Comment by textloop** [comment]
Danke!
