### ISSUE TITLE
Optionen im Header: lb

### ISSUE THREAD

**Issue by haoess** [deutschestextarchiv/dtabf#78]
Es wäre sinnvoll, in einer Art Optionenliste im Header klar zu definieren, wie der Gebrauch von `<lb/>` im Dokument stattfindet:

* kennzeichnet `<lb/>` Zeilenanfang oder -ende?
* wird `<lb/>` vorlagengetreu umgesetzt oder nicht?
* soll in der Darstellung das Attribut `@n` umgesetzt werden?

**Comment by haoess** [comment]
Siehe auch #33, wobei ich die automatische Konvertierung eines Dokuments von `<lb/>` = Zeilenende nach `<lb/>` = Zeilenanfang, vor allem des DTA-Gesamtkorpus, für illusorisch halte.

**Comment by funkyfuture** [comment]
> kennzeichnet <lb/> Zeilenanfang oder -ende?

nme sollten explizit nur abweichungen gekennzeichnet werden. ich fage mich, wer / welches verarbeitende system mit solchen kennzeichnungen informiert werden soll. also warum wäre es sinnvoll, die möglichen metadaten weiter ~~aufzublähen~~ auszudehnen? so wie ich das wahrnehme, spricht sich die community klar für eine angleichung des DTAbf an TEI P5 aus, während das DTA mit seiner legacy umgehen muss. oder gibt es weitere motivationen?

> soll in der Darstellung das Attribut @n umgesetzt werden?

darstellungsoptionen sind eine angelegenheit der applikation, nicht des transkriptionsformats, oder?

ich hätte es auch besser gefunden, die diskussion in #33 beisammen zu halten.

ein frohes und besinnliches fest!

**Comment by haoess** [comment]
Was @funkyfuture sagt.
