### ISSUE TITLE
Status of this repository and its branches

### ISSUE THREAD

**Issue by wrznr** [deutschestextarchiv/dtabf#79]
The last (i.e. latest) commit to master dates back to 2017. Many issues describe errors or start discussions which at some point drift off to inactivity. On the other hand the branch `dev` receives updates quite regularly. What is the definite version of DTABf? Is it more useful to use the `dev` branch instead of the seemingly stale master? What can we expect from the DTABf in the future?

**Comment by xlhrld** [comment]
Related to #56. It would be really good to be clear on this matter – and to release more often!

**Comment by funkyfuture** [comment]
given that there are three unmerged pull requests that i opened and Kay's post made me aware of the `dev` branch for the first time, i think a document that describes the process of and the requirements for contributions would be very helpful.

> and to release more often!

to me it would be more important that the introduced changes are consistent.

**Comment by susannehaaf** [comment]
The new version 1.1.0 was prepared in the dev branch and released today. Development of the format will be further pursued in the dev branch which seems to be common practice. New, complete versions will be pushed to the master. Pull requests should rather be opened in the dev branch. I'm closing the existing open pull requests without merge but I will prepare the proposed enhancements for the next version. 

Please note that we released [the DTABf Guiding Principles](http://deutschestextarchiv.de/doku/basisformat/leitlinien.html) containing information on how further development of the format is conducted.

**Comment by wrznr** [comment]
Many thanks for the clarification and many thanks for the new version!

It would be possible to just use the master branch if the *releases* mechanism provided by GitHub would be used for making releases.
