### ISSUE TITLE
Documentation: Grammar issue

### ISSUE THREAD

**Issue by bwbohl** [deutschestextarchiv/dtabf#81]
https://github.com/deutschestextarchiv/dtabf/blob/1f1af160f01a35db6208a0acf1c22c3cea4dbdca/documentation/trZeichensetzungAllg.dita#L22

This sentence need some grammar correction, e.g.
` Der Abdruck, den ein beim Druckvorgang heruntergefallenes Spatium auf der Seite…`

or
´ Der Abdruck, eines beim Druckvorgang heruntergefallenen Spatiums auf der Seite`

**Comment by susannehaaf** [comment]
Thanks for the info. I corrected the error (see dev branch) -- it will be in master and online with the next release.

**Comment by bwbohl** [comment]
closed with 6152c95b8fd5af5d1420f185a6e9fa04c9c1425b
