### ISSUE TITLE
Encoding line endings

### ISSUE THREAD

**Issue by bwbohl** [deutschestextarchiv/dtabf#82]
The DTABf documentation states that line endings are to be marked up using the tei:leb element:

https://github.com/deutschestextarchiv/dtabf/blob/ee9a0d580804c8ec36c127d7fecf986440c7eea1/documentation/lbAllg.dita#L8

The TEI Guidelines (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-lb.html) state that the tei:lb element is used to markup line beginnings, though. This also was true for TEI v3.0.0

**Comment by cthomasdta** [comment]
Thank you, please see disussion in https://github.com/deutschestextarchiv/dtabf/issues/33

**Comment by bwbohl** [comment]
thanks for pointing me to #33 
closing this ticket as it clearly is a duplicate
