### ISSUE TITLE
dtabf / documentation

### ISSUE THREAD

**Issue by cthomasdta** [deutschestextarchiv/dtabf#9]
So weit ich sehe, ist der Fall der d-Abbreviatur noch nicht eindeutig festgelegt (Erfassungs- und Kodierungsrichtlinien). Wir haben in der Vergangenheit zwei Lösungen empfohlen:

Statt `<choice><abbr>ð</abbr><expan>der</expan></choice>` oder anderer Dinge:

besser `U+010F LATIN SMALL LETTER D WITH CARON` (z.B. an Dominik Stoltz empfohlen) oder 
ein "d" mit anschließendem `U+0315 COMBINING COMMA ABOVE RIGHT` (so die Einigung mit der Gruppe Glonging damals).

Laut Statistik http://www.deutschestextarchiv.de/dtaq/stat/alphabet ist der letztere Weg häufiger gewählt worden.

Wir sollten das vereinheitlichen und in die Doku aufnehmen.

**Comment by susannehaaf** [comment]
Fixed (version 1.1.0)
