### ISSUE TITLE
Kodierung von Listen, innerhalb von <item>, <label> erlauben

### ISSUE THREAD

**Issue by sgoettel** [deutschestextarchiv/dtabf#94]
Inbesondere bei verschachtelten Listen, wie schön im [Bsp der DTABf-Doku zu sehen](http://www.deutschestextarchiv.de/doku/basisformat/liVerschachtelt.html) ist, wäre die Möglichkeit der Auszeichnung der einzelnen Punkte (labels) innerhalb eines <item> sinnvoll.

[siehe dazu auch die TEI-Doku](https://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-label.html)

 ```
<list>
  <item>
   <label>1.</label> Der Dorschenhammer oder das obere Schauensteiner Hammer-<lb/>
   werk an der Selbitz war ein Stabfeuer, das sein Roheisen<lb/>
   von dem Hochofen zu Thiemitz, an dem es zur Hälfte be-<lb/>
   teiligt war, erhielt.
  </item><lb/>
  </list>
```

**Comment by cthomasdta** [comment]
Daumen hoch für `<label>`, nicht nur in `<list>`! Brauche ich auch in `<p>`

**Comment by cthomasdta** [comment]
> Daumen hoch für `<label>`, nicht nur in `<list>`! Brauche ich auch in `<p>`

= jetzt ausgelagert, da eigene Diskussion, in #98

**Comment by cthomasdta** [comment]
@susannehaaf nur Rückfragen, nach heutigem Beschluss, zur Sicherheit: du hattest geschrieben: 

> #94 (keine Schemaänderung, nur Doku-Änderung nötig)

aber es ist doch eine Schemaänderung nötig, oder?!

**Comment by susannehaaf** [comment]
Eigentlich nicht. Das Verhalten von grundsätzlich erlaubten Elementen zueinander ist im DTABf-ODD technisch gegenüber den TEI-Richtlinien nicht geändert. Im Schematron-Regelsatz gibt es einige entsprechende Regeln. Ansonsten werden Constraints über die Doku festgelegt.

**Comment by susannehaaf** [comment]
Können wir dieses Ticket schließen, weil es #98 jetzt gibt (@sgoettel ; @cthomasdta )?

**Comment by sgoettel** [comment]
Danke für die Rückmeldung!
