### ISSUE TITLE
DFG-Viewer auch für DTA (nicht nur DTAQ)

### ISSUE THREAD

**Issue by sgoettel** [deutschestextarchiv/dtabf#95]
Die Funktion, sich Werke im DFG-Viewer anzeigen zu lassen, sollte nicht nur für eingeloggte User im DTAQ zur Verfügung stehen, sondern auch, vermutlich unter `Ansichten für dieses Werk`, im DTA selber.

**Comment by cthomasdta** [comment]
= kein DTABf-Issue, bitte mantis Ticket, wohl zunächst an Matthias Boenig

**Comment by sgoettel** [comment]
sehr richtig! Danke
